Repository appuio/component-control-api, pull requests merged in 2022-03, with the labels that each got.

#14 Update to control API `v0.5.1`
  class/defaults.yml
  tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/defaults/control-api/control-api/01_crds.yaml
  tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/01_crds.yaml
Labels: enhancement

#15 Update to control API v0.5.2
  class/defaults.yml
  tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/defaults/control-api/control-api/10_rbac_organization.yaml
  tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/10_rbac_organization.yaml
Labels: bug

#16 Update dependency ghcr.io/appuio/control-api to v0.5.3
  class/defaults.yml
  tests/golden/defaults/control-api/control-api/01_api_server/01_role.yaml
  tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/defaults/control-api/control-api/10_rbac_organization.yaml
  tests/golden/insecure/control-api/control-api/01_api_server/01_role.yaml
  tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/10_rbac_organization.yaml
Labels: dependency

#17 Add IDP adapter deployment
  class/control-api.yml
  class/defaults.yml
  component/idp-adapter.libsonnet
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/defaults.yml
  tests/golden/defaults/control-api/control-api/30_idp_adapter.yaml
Labels: enhancement

#20 Update modulesync config
  .sync.yml
Labels: ignore

#18 Update dependency ghcr.io/vshn/appuio-keycloak-adapter to v0.5.0
  class/defaults.yml
  tests/golden/defaults/control-api/control-api/30_idp_adapter.yaml
Labels: dependency

#22 Bump `vshn/appuio-keycloak-adapter` to `v0.5.1`
  class/defaults.yml
  tests/golden/defaults/control-api/control-api/30_idp_adapter.yaml
Labels: dependency

#23 Update dependency ghcr.io/vshn/appuio-keycloak-adapter to v0.5.2
  class/defaults.yml
  tests/golden/defaults/control-api/control-api/30_idp_adapter.yaml
Labels: dependency

#25 Simplify dependency fetching
  class/control-api.yml
  component/api-server.jsonnet
  component/rbac-basic-user.libsonnet
  component/rbac-organization.libsonnet
Labels: ignore

#24 Update dependency ghcr.io/appuio/control-api to v0.7.0
  class/defaults.yml
  tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/defaults/control-api/control-api/02_api_controller/01_role.yaml
  tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/02_api_controller/01_role.yaml
  tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml
Labels: dependency

#27 Update dependency ghcr.io/appuio/control-api to v0.7.1
  class/defaults.yml
  tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/defaults/control-api/control-api/02_api_controller/01_role.yaml
  tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml
  tests/golden/defaults/control-api/control-api/10_rbac_organization.yaml
  tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/02_api_controller/01_role.yaml
  tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/10_rbac_organization.yaml
Labels: dependency

#28 Fix APIService name in how-to
  docs/modules/ROOT/pages/how-tos/tls.adoc
Labels: documentation

#31 Add missing parameter docs for `username_prefix` and `extraArgs`
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: documentation

#30 Add configuration for admission webhook
  class/defaults.yml
  component/api-controller.jsonnet
  docs/modules/ROOT/pages/how-tos/tls.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/defaults.yml
  tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml
  tests/golden/defaults/control-api/control-api/02_api_controller/10_webhook_cert_secret.yaml
  tests/golden/defaults/control-api/control-api/02_api_controller/10_webhook_config.yaml
  tests/golden/defaults/control-api/control-api/02_api_controller/11_webhook_service.yaml
  tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/02_api_controller/10_webhook_cert_secret.yaml
  tests/golden/insecure/control-api/control-api/02_api_controller/10_webhook_config.yaml
  tests/golden/insecure/control-api/control-api/02_api_controller/11_webhook_service.yaml
  tests/insecure.yml
Labels: enhancement

#32 Fix webhook TLS secret reference
  component/api-controller.jsonnet
  tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml
Labels: bug

#33 Update appuio/control-api to v0.8.2
  class/defaults.yml
  tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml
Labels: dependency
