Repository appuio/component-control-api, pull requests merged in 2023-04, with the labels that each got.

#76 Update dependency ghcr.io/appuio/control-api to v0.24.0
  class/defaults.yml
  tests/golden/defaults/control-api/control-api/01_api_server/01_role.yaml
  tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml
  tests/golden/defaults/control-api/control-api/10_rbac_basic_user.yaml
  tests/golden/insecure/control-api/control-api/01_api_server/01_role.yaml
  tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/10_rbac_basic_user.yaml
Labels: dependency

#77 Update dependency ghcr.io/appuio/control-api to v0.24.1
  class/defaults.yml
  tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml
Labels: dependency

#79 Fixup billing country list mount path
  component/api-server.jsonnet
  tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/01_api_server/01_countries_configmap.yaml
  tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml
  tests/insecure.yml
Labels: ignore

#80 Add runbook for "E-Mail Sending Stuck" alert
  docs/modules/ROOT/pages/runbooks/InvitationEmailStuck.adoc
  docs/modules/ROOT/partials/nav.adoc
  docs/modules/ROOT/partials/runbooks/contribution_note.adoc
Labels: documentation

#81 Extend country list
  class/defaults.yml
  tests/golden/defaults/control-api/control-api/01_api_server/01_countries_configmap.yaml
Labels: change

#82 Always restart apiserver when the country list is updated
  component/api-server.jsonnet
  tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml
Labels: enhancement

#84 Update ghcr.io/appuio/control-api Docker tag to v0.25.1
  class/defaults.yml
  tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/defaults/control-api/control-api/02_api_controller/01_role.yaml
  tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/02_api_controller/01_role.yaml
  tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml
Labels: dependency

#86 Add cronjob for running cleanup command
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  class/defaults.yml
  component/cleanup-cronjob.libsonnet
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/withcronjob/control-api/apps/control-api.yaml
  tests/golden/withcronjob/control-api/control-api/00_namespace.yaml
  tests/golden/withcronjob/control-api/control-api/01_api_server/01_countries_configmap.yaml
  tests/golden/withcronjob/control-api/control-api/01_api_server/01_role.yaml
  tests/golden/withcronjob/control-api/control-api/01_api_server/01_role_binding.yaml
  tests/golden/withcronjob/control-api/control-api/01_api_server/01_role_binding_auth_delegator.yaml
  tests/golden/withcronjob/control-api/control-api/01_api_server/01_service_account.yaml
  tests/golden/withcronjob/control-api/control-api/01_api_server/02_apiservice.yaml
  tests/golden/withcronjob/control-api/control-api/01_api_server/02_certs.yaml
  tests/golden/withcronjob/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/withcronjob/control-api/control-api/01_api_server/02_service.yaml
  tests/golden/withcronjob/control-api/control-api/01_crds.yaml
  tests/golden/withcronjob/control-api/control-api/02_api_controller/01_leader_election_role.yaml
  tests/golden/withcronjob/control-api/control-api/02_api_controller/01_leader_election_role_binding.yaml
  tests/golden/withcronjob/control-api/control-api/02_api_controller/01_role.yaml
  tests/golden/withcronjob/control-api/control-api/02_api_controller/01_role_binding.yaml
  tests/golden/withcronjob/control-api/control-api/02_api_controller/01_service_account.yaml
  tests/golden/withcronjob/control-api/control-api/02_api_controller/02_deployment.yaml
  tests/golden/withcronjob/control-api/control-api/02_api_controller/10_webhook_cert_secret.yaml
  tests/golden/withcronjob/control-api/control-api/02_api_controller/10_webhook_config.yaml
  tests/golden/withcronjob/control-api/control-api/02_api_controller/11_webhook_service.yaml
  tests/golden/withcronjob/control-api/control-api/10_rbac_basic_user.yaml
  tests/golden/withcronjob/control-api/control-api/10_rbac_cluster_admin_impersonation.yaml
  tests/golden/withcronjob/control-api/control-api/10_rbac_organization.yaml
  tests/golden/withcronjob/control-api/control-api/20_cronjob.yaml
  tests/golden/withcronjob/control-api/control-api/20_zones.yaml
  tests/golden/withcronjob/control-api/control-api/30_idp_adapter.yaml
  tests/withcronjob.yml
Labels: enhancement

#87 Update ghcr.io/appuio/control-api Docker tag to v0.26.0
  class/defaults.yml
  tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml
  tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml
Labels: dependency
